### ISSUE TITLE
Responsive foot cart

### ISSUE THREAD

**Issue by ChauNgocMinh** [ChauNgocMinh/BookShop#1]
PC: 1920x1080
Laptop: 1366x768
ipad: 1200px
Laptop: 400px

**Comment by nguyentranthanhliem221002** [comment]
hi

**Comment by nguyentranthanhliem221002** [comment]
ok

**Comment by nguyentranthanhliem221002** [comment]
<section class="navigation">
    <div class="nav-container">
        <div class="brand">
            <a href="#!">🍀 Clover Clothing</a>
        </div>
        <nav>
            <div class="nav-mobile">
                <a id="nav-toggle" href="#!"><span></span></a>
            </div>
            <ul class="nav-list">
                <li><a href="#!">Home</a></li>
                <li><a href="#!">Shop</a></li>
                <li>
                    <a href="#!">Services</a>
                    <ul class="nav-dropdown">
                        <li><a href="#!">Web Design</a></li>
                        <li><a href="#!">Web Development</a></li>
                        <li><a href="#!">Graphic Design</a></li>
                    </ul>
                </li>
                <li><a href="#!">About Us</a></li>
                <li><a href="#!">Contact</a></li>
            </ul>
        </nav>
    </div>
</section>
<app-home></app-home>

    <div class="footer">
        <div class="box d-flex">
            <div>
                <h1>dgrgfdbfdbfb</h1>
                <h3>fdsfsdfsdfsdvsdgvsvdsds</h3>
            </div>
            
            <button>Click</button>
        </div>
        <div class="container d-flex justify-content-between">
            
            <ul class="item">
                <div class="first_item">COLORLIB</div>
                <li>@2019</li>
            </ul>
            <ul class="item">
                <div class="first_item">Customer</div>
                <li>Buyer</li>
                <li>Supplier</li>
            </ul>
            <ul class="item">
                <div class="first_item">Company</div>
                <li>About us</li>
                <li>Careers</li>
                <li>Contact us</li>
            </ul>
            <ul class="item">
                <div class="first_item">Add</div>
                <li>Tems & Conditions</li>
                <li> Privacy Policy</li>
            </ul>
            <ul class="item">
                <div class="first_item">Follow us</div>
                <div class="d-flex">
                    <li><i class="fa-brands fa-facebook"></i></li>
                    <li><i class="fa-brands fa-twitter"></i></li>
                    <li><i class="fa-brands fa-linkedin"></i></li>
                    <li><i class="fa-solid fa-paper-plane"></i></li>
                </div>

            </ul>

        </div>
    </div>

**Comment by nguyentranthanhliem221002** [comment]
$content-width: 1000px;
$breakpoint: 799px;
$nav-height: 70px;
$nav-background: #fff;
$nav-font-color: #0c0c0c;
$link-hover-color: #f8b500;

@import url('https://fonts.googleapis.com/css?family=Poppins&display=swap');


body {
    font-family: 'Poppins'
}

.navigation {
    height: $nav-height;
    background: $nav-background;
}

.nav-container {
    max-width: $content-width;
    margin: 0 auto;
}

.brand {
    position: absolute;
    padding-left: 20px;
    float: left;
    line-height: $nav-height;
    text-transform: uppercase;
    font-size: 1.4em;

    &:hover {}

    a,
    a:visited {
        color: $nav-font-color;
        text-decoration: none;
    }
}

nav {
    float: right;

    ul {
        list-style: none;
        margin: 0;
        padding: 0;

        li {
            float: left;
            position: relative;

            a {
                display: block;
                padding: 10px 20px 0 20px;
                line-height: 50px;
                background: $nav-background;
                color: $nav-font-color;
                text-decoration: none;


                &::before {
                    transition: 300ms;
                    height: 5px;
                    content: "";
                    position: absolute;
                    background-color: $link-hover-color;
                    width: 0%;
                    bottom: 0px;
                }

                &:hover::before {
                    width: 70%;
                }

                &:not(:only-child):after {
                    padding-left: 4px;
                    content: ' ▾';
                }
            }

            // Dropdown list
            ul li {
                min-width: 190px;

                a {
                    padding: 15px;
                    line-height: 20px;
                }
            }
        }
    }
}


.nav-dropdown {
    display: none;
    position: absolute;
    z-index: 1;
    box-shadow: 0 3px 12px rgba(0, 0, 0, 0.15);
}

.nav-mobile {
    display: none;
    position: absolute;
    top: 0;
    right: 0;
    background: $nav-background;
    height: $nav-height;
    width: $nav-height;
}

@media only screen and (max-width: $breakpoint) {
    .nav-mobile {
        display: block;
    }

    nav {
        width: 100%;
        padding: $nav-height 0 15px;

        ul {
            display: none;

            li {
                float: none;

                a {
                    padding: 15px;
                    line-height: 20px;

                    &:hover::before {
                        width: 20%;
                    }
                }

                ul li a {
                    padding-left: 30px;
                }
            }
        }
    }

    .nav-dropdown {
        position: static;
    }
}

#nav-toggle {
    position: absolute;
    left: 18px;
    top: 22px;
    cursor: pointer;
    padding: 10px 35px 16px 0px;

    span,
    span:before,
    span:after {
        cursor: pointer;
        border-radius: 1px;
        height: 5px;
        width: 35px;
        background: $link-hover-color;
        position: absolute;
        display: block;
        content: '';
        transition: all 300ms ease-in-out;
    }

    span:before {
        top: -10px;
    }

    span:after {
        bottom: -10px;
    }

    &.active span {
        background-color: transparent;

        &:before,
        &:after {
            top: 0;
        }

        &:before {
            transform: rotate(45deg);
        }

        &:after {
            transform: rotate(-45deg);
        }
    }
}

@media screen and (min-width: $breakpoint) {
    .nav-list {
        display: block !important;
    }
}
.footer{
    
    position: relative;
    padding: 150px 0 80px 0;

    display: flex;

    background-color:#171c28;

    height: auto;

    justify-content: space-around;

    .box{
        top:-30px;
        background-color: #8387d1;
        height: auto;
        width: 850px;
        padding: 20px;
        position: absolute;
        justify-content: space-between;
        align-items: center;
        box-shadow:  -15px -15px 10px #8387d17e;
        // opacity: ;

  
        h1{
            color: #fff;
        }
        h3{
            color: 32365c;
        }
        button{
            width: 100px;
            height: 50px; 
            background-color: #171c28;
            color: #fff;
            border: none ;
            
        }
        button:hover{
            opacity: 0.7;

            transition: linear 0.7s;

        }
    }

    .container{
        .item{
            color:#fff ;
            
            li{
                list-style: none;

                margin-right: 10px;

                color: #545962;
            }

            .first_item{
                 
            }

        }
    }
}
